# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0
#
# The files to vendor (copy).
# See {repo}/cmd/k8scopy/main.go for more info.
module: k8s.io/apimachinery
version: v0.19.8
packages:
- name: pkg/api/resource
  files:
  - amount.go
  - math.go
  - quantity.go
  - scale_int.go
  - suffix.go
