name: Qlik release

on:
  push:
    tags:
      - 'qlik/v*.*.*'

jobs:
  test-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test
        run: |
          make qlik-test-api-plugins

      - name: build all
        run: |
          QLIK_VERSION=${GITHUB_REF/refs\/tags\//} make qlik-build-all

      - name: release
        run: |
          set -x
          QLIK_VERSION=${GITHUB_REF/refs\/tags\//}

          if gh release view "${QLIK_VERSION}"; then
            gh release upload "${QLIK_VERSION}" ./bin/*.tar.gz --clobber
          else
            gh release create "${QLIK_VERSION}" -n "${QLIK_VERSION}" -p ./bin/*.tar.gz
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
